#: import main main
rootWidget:
    EventForm

<EventForm>:
    BoxLayout:
        Label:
            text:"event"
        Button:
            text:"send text"
            on_press: main.ChangeForm().Print(self.text)
        Button:
            text:"clear widgets"
            on_press:app.root.clear_widget()
        Button:
            text: "change widgets"
            on_press: app.root.new_widget()
