AddLocationForm:

<AddLocationForm>:
    orientation:"vertical"
    search_input: search_box

    BoxLayout:
        size_hint_y: None
        height: "40dp"

        TextInput:
            id:search_box
            size_hint_x:50

        Button:
            text:"search"
            size_hint_x: 25
            on_press: root.search_location()

        Button:
            size_hint_x:25
            text:"current location"

    ListView:
        item_strings:["dsa", "pd"]
